#ifndef __RADIO_HAL_COMMON_H
#define   __RADIO_HAL_COMMON_H

#include "sys.h"

#define SIZE_INFRAME_Q			2

#define MRFI_RX_METRICS_SIZE		2

#define FI_AVAILABLE			0
#define FI_INUSE_UNTIL_DEL		1

#define TRF_MSG_VERSION			0x01

#define TRF_MSG_REBOOT			24
#define TRF_MSG_HEART			27
#define TRF_MSG_DEFAULT			49
#define TRF_MSG_SENSITIVITY		50
#define TRF_MSG_WORKMODE			51
#define TRF_MSG_INITBACKGROUND	52
#define TRF_MSG_BASICINFO		53
#define TRF_MSG_UPGRADE			54
#define TRF_MSG_STATUS			55
#define TRF_MSG_HEART_BOOTLOADER	56
#define TRF_MSG_RFHEART_INTERVAL	57
#define TRF_MSG_DEBUG_INFO		58
#define TRF_MSG_DEBUG_STATUS		58
#define TRF_MSG_REMOTE_SERVER		59
#define TRF_MSG_DYNAMICINFO		60
#define TRF_MSG_JSON			61
#define TRF_MSG_GENERAL_CMD		62

















#endif /* __RADIO_HAL_COMMON_H */
