#ifndef __HAL_TEST_BENCH_H
#define   __HAL_TEST_BENCH_H

#include "sys.h"

#define	TESTBENCH_ERASER_FLASHSN_DISABLE	0
#define	TESTBENCH_ERASER_FLASHSN_ENABLE	1
#define	TESTBENCH_ERASER_FLASHSN_TYPE		TESTBENCH_ERASER_FLASHSN_ENABLE

bool TestBench_FLASH_CheckSubSN(void);
void TestBench_FLASH_WriteSubSN(void);

#endif /* __HAL_TEST_BENCH_H */
